#!/usr/bin/env bun
/**
 * Fetch per-version "What's New" text from App Store Connect for TrueNAS Pulse.
 * Writes /app/repos/truenas-pulse-site/src/data/changelog.ts
 *
 * Reuses the same JWT + key files as /app/scripts/appstore-query.ts.
 */
import { createSign } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const AUTH = JSON.parse(readFileSync("/app/data/appstore-auth.json", "utf-8")) as {
  issuer_id: string;
  key_id: string;
};
const KEY = readFileSync("/app/data/appstore-private-key.pem", "utf-8");
const BASE = "https://api.appstoreconnect.apple.com/v1";
const APP_ID = "6759870893";

function jwt(): string {
  const header = Buffer.from(
    JSON.stringify({ alg: "ES256", kid: AUTH.key_id, typ: "JWT" }),
  ).toString("base64url");
  const now = Math.floor(Date.now() / 1000);
  const payload = Buffer.from(
    JSON.stringify({
      iss: AUTH.issuer_id,
      iat: now,
      exp: now + 1200,
      aud: "appstoreconnect-v1",
    }),
  ).toString("base64url");
  const msg = `${header}.${payload}`;
  const sig = createSign("SHA256");
  sig.update(msg);
  return `${msg}.${sig.sign({ key: KEY, dsaEncoding: "ieee-p1363" }, "base64url")}`;
}

async function api(path: string): Promise<any> {
  const r = await fetch(`${BASE}${path}`, {
    headers: { Authorization: `Bearer ${jwt()}` },
  });
  if (!r.ok) throw new Error(`HTTP ${r.status} ${await r.text()}`);
  return r.json();
}

// 1. List app store versions
const versionsResp = await api(
  `/apps/${APP_ID}/appStoreVersions?limit=20`,
);
const versions = (versionsResp.data as any[])
  .filter((v) => v.attributes.appStoreState === "READY_FOR_SALE")
  .map((v) => ({
    id: v.id as string,
    version: v.attributes.versionString as string,
    createdDate: v.attributes.createdDate as string,
    earliestReleaseDate: v.attributes.earliestReleaseDate as string | null,
  }));

console.log(`found ${versions.length} live versions`);

// 2. For each version, fetch the en-US localization (whatsNew) AND the build
// uploadedDate, which is a much closer proxy for the actual release date than
// the version's createdDate (which is when the operator drafted the listing).
const out: Array<{
  version: string;
  releaseDate: string;
  whatsNew: string;
}> = [];

// Hardcoded fallbacks for go-live dates that the API returns wrong/stale.
// Source: itunes.apple.com/lookup currentVersionReleaseDate (authoritative).
const knownReleaseDates: Record<string, string> = {
  "1.0": "2026-04-07",
  "1.0.3": "2026-04-25",
};

for (const v of versions) {
  const locResp = await api(
    `/appStoreVersions/${v.id}/appStoreVersionLocalizations?fields[appStoreVersionLocalizations]=locale,whatsNew&limit=20`,
  );
  const enUS = (locResp.data as any[]).find(
    (l) => l.attributes.locale === "en-US",
  );
  const whatsNew = enUS?.attributes?.whatsNew?.trim() ?? "";

  // Build attached to this version: its uploadedDate is when the binary
  // landed, which is within ~24h of the App Store release.
  let releaseDate = knownReleaseDates[v.version];
  if (!releaseDate) {
    try {
      const buildResp = await api(`/appStoreVersions/${v.id}/build`);
      const buildId = (buildResp.data as any)?.id;
      if (buildId) {
        const build = await api(`/builds/${buildId}`);
        const uploaded = (build.data as any)?.attributes?.uploadedDate as
          | string
          | undefined;
        if (uploaded) releaseDate = uploaded.split("T")[0];
      }
    } catch {
      /* fall through to createdDate */
    }
  }
  if (!releaseDate)
    releaseDate = v.earliestReleaseDate ?? v.createdDate.split("T")[0];

  out.push({ version: v.version, releaseDate, whatsNew });
  console.log(
    `  ${v.version} — ${releaseDate}  ${whatsNew ? `(${whatsNew.length} chars)` : "(no notes)"}`,
  );
}

// Sort newest first
out.sort((a, b) => b.version.localeCompare(a.version, undefined, { numeric: true }));

// 3. Write the manifest the changelog page imports
const tsOut = `/**
 * Auto-generated by /app/data/pulse-screenshots/fetch-changelog.ts.
 * Pulled from App Store Connect (appStoreVersionLocalizations endpoint).
 *
 * Refresh: bun run /app/data/pulse-screenshots/fetch-changelog.ts
 */
export interface ChangelogEntry {
  version: string;
  /** ISO date (YYYY-MM-DD) — when the version went live in the App Store. */
  releaseDate: string;
  /** Verbatim "What's New" text from App Store Connect, leading bullets included. */
  whatsNew: string;
}

export const changelog: ChangelogEntry[] = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(
  "/app/repos/truenas-pulse-site/src/data/changelog.ts",
  tsOut,
);
console.log(
  `\nwrote ${out.length} entries to src/data/changelog.ts`,
);
