/**
 * Auto-generated by /app/data/pulse-screenshots/fetch-changelog.ts.
 * Pulled from App Store Connect (appStoreVersionLocalizations endpoint).
 *
 * Refresh: bun run /app/data/pulse-screenshots/fetch-changelog.ts
 */
export interface ChangelogEntry {
  version: string;
  /** ISO date (YYYY-MM-DD) — when the version went live in the App Store. */
  releaseDate: string;
  /** Verbatim "What's New" text from App Store Connect, leading bullets included. */
  whatsNew: string;
}

export const changelog: ChangelogEntry[] = [
  {
    "version": "1.0.4",
    "releaseDate": "2026-05-04",
    "whatsNew": "• Clearer health and alert screens, so important server issues are easier to review.\n• Better visibility into backups, data protection tasks, and TrueNAS updates.\n• More useful storage, dataset, share access, and configuration checks.\n• Activity entries now give more context when something needs attention.\n• Dashboard, search, audit log, and loading flows are smoother and more reliable.\n• Key settings stay available more often when the server connection is interrupted.\n• Improved compatibility with newer TrueNAS SCALE releases."
  },
  {
    "version": "1.0.3",
    "releaseDate": "2026-04-25",
    "whatsNew": "• Improved System Health summaries with clearer READY, WARNING, and CRITICAL status details\n• Improved Push Relay enrollment handling to prevent sync race conditions\n• Dashboard refresh and navigation issues that could affect routing or stale data handling\n• Live Activity build compatibility with newer Swift/Xcode versions"
  },
  {
    "version": "1.0.2",
    "releaseDate": "2026-04-16",
    "whatsNew": "System Health: expanded security checks, calmer scoring, clearer severity labels\nAccurate storage runway projections per pool\nFaster, clearer search and command palette\nUI polish pass: refined typography, haptics, and smoother banners\nPlainer connection and certificate trust language\nCalmer, contextual upgrade prompts with live pricing\nFixes: boot pool icon, route snapshots, action log labels"
  },
  {
    "version": "1.0.1",
    "releaseDate": "2026-04-08",
    "whatsNew": "Add TrueNAS 26 webshare support and compatibility fixes"
  },
  {
    "version": "1.0",
    "releaseDate": "2026-04-07",
    "whatsNew": ""
  }
];
