/**
 * Auto-generated by /app/data/pulse-screenshots/build.mjs.
 * To regenerate: bun run /app/data/pulse-screenshots/build.mjs
 */
export interface Screenshot {
  slug: string;
  title: string;
  caption: string;
  tier: "Pro" | null;
  /** Source PNG dimensions — preserve aspect ratio for the gallery. */
  width: number;
  height: number;
}

export const screenshots: Screenshot[] = [
  {
    "slug": "01-dashboard",
    "title": "Your Pulse. Within Reach.",
    "caption": "CPU, memory, storage, and network — live, right now.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "02-storage",
    "title": "Full ZFS Visibility",
    "caption": "Pool health, capacity, snapshots, and disk count — without the browser.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "03-sharing",
    "title": "Shares and Sessions",
    "caption": "SMB, NFS, and connected client sessions — all in one place.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "04-workloads",
    "title": "Workload Lifecycle",
    "caption": "Services, VMs, apps, and containers — with update awareness baked in.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "05-fleet",
    "title": "All Your Servers. One Screen.",
    "caption": "Anomaly-first overview across every system. Health, storage, and drift in one view.",
    "tier": "Pro",
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "06-reporting",
    "title": "See Trends Before Incidents",
    "caption": "Historical CPU, memory, network, and disk throughput — beyond the free 1H view.",
    "tier": "Pro",
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "07-widget",
    "title": "Server Health on Your Home Screen",
    "caption": "Glanceable status — no app launch needed.",
    "tier": null,
    "width": 1206,
    "height": 2622
  }
];
