/**
 * Auto-generated by /app/data/pulse-screenshots/build.mjs.
 * To regenerate: bun run /app/data/pulse-screenshots/build.mjs
 */
export interface Screenshot {
  slug: string;
  title: string;
  caption: string;
  tier: "Pro" | null;
  /** Source PNG dimensions — preserve aspect ratio for the gallery. */
  width: number;
  height: number;
}

export const screenshots: Screenshot[] = [
  {
    "slug": "01-dashboard",
    "title": "Know Server Health Fast",
    "caption": "Live health, alerts, storage, and load in one first check.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "02-storage",
    "title": "See Storage Risk Early",
    "caption": "Know whether pools are healthy, filling, or degraded before opening the web UI.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "03-sharing",
    "title": "Check Sharing State",
    "caption": "Review SMB, NFS, and active sessions without leaving your phone.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "04-workloads",
    "title": "Control Operational State",
    "caption": "Track services, VMs, apps, and containers before deciding whether action is needed.",
    "tier": null,
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "05-fleet",
    "title": "Find the Problem Server",
    "caption": "Spot the system that needs attention across health, storage, and drift.",
    "tier": "Pro",
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "06-reporting",
    "title": "Know When It Started",
    "caption": "Use history to place CPU, memory, network, and disk changes on the incident timeline.",
    "tier": "Pro",
    "width": 1206,
    "height": 2622
  },
  {
    "slug": "07-widget",
    "title": "Passive Home Screen Awareness",
    "caption": "Keep server health visible without opening the app.",
    "tier": null,
    "width": 1206,
    "height": 2622
  }
];
